---
title: "Homework 6"
output: github_document
---

```{r}
library(tidyverse)
library(viridis)

library(modelr)
library(mgcv)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

```{r}
birthweight_df = 
  read_csv("data/birthweight.csv") %>% 
  mutate(babysex = as.factor(babysex), 
         fincome = fincome*100, 
         frace = as.factor(frace), 
         malform = as.factor(malform), 
         mrace = as.factor(mrace)) 
```

Checking for missing values by grouping by factor variables to identify possible values: 

```{r}
birthweight_df %>% 
  group_by(babysex) %>% 
  summarize()

birthweight_df %>% 
  group_by(frace) %>% 
  summarize()

birthweight_df %>% 
  group_by(malform) %>% 
  summarize()

birthweight_df %>% 
  group_by(mrace) %>% 
  summarize()

birthweight_df

birthweight_df %>% 
  drop_na()

```

There are no missing values based on the drop NA function 

** OTHER NA OPTIONS? 

Fitting models

```{r}
birthweight_df %>% 
  ggplot(aes(x = blength, y = bwt)) +
  geom_point()

birthweight_df %>% 
  ggplot(aes(x = malform, y = bwt)) +
  geom_point(alpha = 0.3)

birthweight_df %>% 
  ggplot(aes(x = momage, y = bwt)) +
  geom_point(alpha = 0.3)

fit_mine = lm(bwt ~ blength + gaweeks + momage + bhead*babysex, data = birthweight_df)

summary(fit_mine)

modelr::add_residuals(birthweight_df, fit_mine) %>% 
  ggplot(aes(x = bwt, y = resid)) + 
  geom_point()

modelr::add_residuals(birthweight_df, fit_mine) %>% 
ggplot(aes(x = resid)) + 
  geom_density() + 
  xlim(-200, 200)

fit_length = lm(bwt ~ blength + gaweeks, data = birthweight_df)

summary(fit_length)

fit_interaction = lm(bwt ~ bhead*blength*babysex, data = birthweight_df)

summary(fit_interaction)
```

## Problem 2

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}

```

bootstrap_weather = 
  weather_df %>% 
    bootstrap(n = 5000, id = "strap_number") %>% 
    mutate(
      models = map(strap, ~lm( tmax ~ tmin, data = .x)), 
      results = map(models, broom::tidy), 
      r_square = broom::glance()
  )



